# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'bootDistZip'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false

- task: CopyFiles@2
  inputs:
    Contents: |
      spring-mq-demoapp-boot/build/distributions/*
      spring-mq-demoapp-boot-admin/build/distributions/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    FlattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'distributionZip'
    publishLocation: 'Container'
