app:
    camel:
        datasource:
            jdbc-url: jdbc:h2:file:./run/idempotentrepodb
server:
    port: 8081
spring:
    activemq:
        broker-url: tcp://localhost:61616
        password: admin
        user: admin
    boot:
        admin:
            client:
                instance:
                    metadata:
                        user:
                            name: adminserver
                            password: secret
                password: boot-app-pass
                url: http://localhost:8080
                username: boot-app
logging:
    level:
        steffan: DEBUG