app:
    camel:
        datasource:
            jndiName: java:comp/env/jdbc/messageIdDataSource
camel:
    springboot:
        main-run-controller: true
management:
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    application:
        basename: spring-mq-demoapp-boot
        name: ${spring.application.basename}-${spring.profiles.active}
        admin:
            enabled: true
    main:
        banner-mode: 'off'
    profiles:
        active: development
logging:
    path: ./log
