app:
    camel:
        datasource:
            jdbc-url: jdbc:h2:file:./run/idempotentrepodb
server:
    port: 8081
spring:
    activemq:
        broker-url: "failover:(tcp://localhost:61616)?\
                    nested.keepAlive=true&\
                    jms.redeliveryPolicy.useExponentialBackOff=true&\
                    jms.redeliveryPolicy.maximumRedeliveries=5&\
                    jms.redeliveryPolicy.initialRedeliveryDelay=1000&\
                    jms.redeliveryPolicy.backOffMultiplier=2"
        password: ENC(d/q1RfnMwBreQxRnN5SJUYVTVroT4Awb2Cu0scR+9FM4aD0Vc4KirhdyQpF7cl1Y)
        user: admin
    boot:
        admin:
            client:
                instance:
                    metadata:
                        user:
                            name: adminserver
                            password: ENC(1RWlxERLwlmy/enIt7iiJcVTO7tgTc+ofH7cubKU6hzKaoYiKWLVADOdSGOy8u0v)
                password: ENC(gDRK8GD/6DoatARtRnlc5Qrtm/EapeJrvL8mkajLiT2Se+hdoAYEUqb/RYi0qYkb)
                url: http://localhost:8080
                username: boot-app
                auto-deregistration: true
logging:
    level:
        steffan: DEBUG

steffan:
    springmqdemoapp:
        sampleservice:
            camel:
                message-id-max-length: 255
            filecopy:
                inputdir: "/home/andreas/temp/input"
                targetdir: "tmp/target"

jasypt:
    encryptor:
        password: secretmasterpassword
