app:
    camel:
        datasource:
            jdbc-url: jdbc:h2:file:./run/idempotentrepodb
server:
    port: 8081
spring:
    activemq:
        broker-url: "failover:(tcp://localhost:61616)?\
                    nested.keepAlive=true&\
                    jms.redeliveryPolicy.useExponentialBackOff=true&\
                    jms.redeliveryPolicy.maximumRedeliveries=5&\
                    jms.redeliveryPolicy.initialRedeliveryDelay=1000&\
                    jms.redeliveryPolicy.backOffMultiplier=2"
        password: admin
        user: admin
    boot:
        admin:
            client:
                instance:
                    metadata:
                        user:
                            name: adminserver
                            password: secret
                password: boot-app-pass
                url: http://localhost:8080
                username: boot-app
logging:
    level:
        steffan: DEBUG

steffan:
    springmqdemoapp:
        sampleservice:
            camel:
                message-id-max-length: 255
            filecopy:
                inputdir: "C:/tmp/input"
                targetdir: "C:/tmp/target"