app:
    camel:
        datasource:
            jndiName: java:comp/env/jdbc/messageIdDataSource
camel:
    springboot:
        main-run-controller: true
management:
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    application:
        basename: spring-mq-demoapp-boot-sampleservice
        name: ${spring.application.basename}-${spring.profiles.active}
        admin:
            enabled: true
    main:
        banner-mode: 'off'
    profiles:
        active: development
    quartz:
        job-store-type: MEMORY
    jta:
        atomikos:
            properties:
                maxTimeout: 60000
                defaultJtaTimeout: 60000
logging:
    path: ./log

jasypt:
    encryptor:
        algorithm: PBEWITHHMACSHA512ANDAES_256
        ivGeneratorClassname: org.jasypt.iv.RandomIvGenerator