application:
    clients:
      - username: admin
        password: "{bcrypt}$2a$10$SA1h5Cn.2JuIUJlOB6Vxse46mSEtRrAJwYY9VvAbuELBcMbkpkI/W"
        roles: READ,WRITE
      - username: boot-app
        password: "{bcrypt}$2a$10$spgV4DWCvRDqs1WZXcF1POQ5wsG4yNMGQv/vuT9hVDBdscNh5tP2W"
        roles: READ,WRITE
      - username: self
        password: "{bcrypt}$2a$10$r5sza.dD0taVuVjPdKvVxeRlRAo9QRUue7HBhwVJvS7gSa6DVAmrS"
        roles: READ,WRITE
spring:
  boot:
    admin:
      client:
        instance:
          metadata:
            user:
              name: self
              password: ENC(h0b6RC9ru/dx1bDzjLrcYtcnwyOakH4/IoGZPBF50ruPiXzR6l2AhK1TTR/YbvQV)
        password: ENC(ixYFJbbIwdPTAL8uY6Fin119DdubPzFShnI67fsY9uCigmbf1Knb0khzVfjd/8Xo)
        url: http://localhost:8080
        username: self

jasypt:
  encryptor:
    password: secretadminmasterpassword