management:
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    application:
        basename: spring-mq-demoapp-boot-admin
        name: ${spring.application.basename}-${spring.profiles.active}
        admin:
            enabled: true
    main:
        banner-mode: 'off'
    profiles:
        active: development
logging:
    path: ./log

jasypt:
    encryptor:
        algorithm: PBEWITHHMACSHA512ANDAES_256
        ivGeneratorClassname: org.jasypt.iv.RandomIvGenerator