management:
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    application:
        basename: spring-mq-demoapp-boot-admin
        name: ${spring.application.basename}-${spring.profiles.active}
    main:
        banner-mode: 'off'
    profiles:
        active: development
